---
# tasks file for app-delpoy

- name : installer dependences
  apt: 
    name: [git, python-pymysql, mysql-client]
    state: present

- name: retirer du balancer
  haproxy:
    state: disabled
    host: '{{ inventory_hostname }}'
    backend: habackend
    socket: /var/lib/haproxy/stats
    fail_on_not_found: yes
    shutdown_sessions: yes
  delegate_to: docker_ansible_lb_1

- git:
    repo: https://gitlab.com/ttwthomas/app-example-php.git
    dest: /var/www/html/app
    force: yes
  register: git_repo

- name: Restorer database
  mysql_db:
    name: cocadmin
    state: import
    target: /var/www/html/app/creer_table.sql
    login_host: docker_ansible_db_1
    login_password: 1234
    login_user: cocadmin
  run_once: true
  when: git_repo.changed

- name: verifier que la page est up
  uri:
    url: http://localhost/app/index.php
    return_content: yes
  register: this
  failed_when: "ansible_hostname not in this.content"

- name: ajouter au balancer
  haproxy:
    state: enabled
    host: '{{ inventory_hostname }}'
    backend: habackend
    socket: /var/lib/haproxy/stats
  delegate_to: docker_ansible_lb_1
