---
- hosts: dev_lb

  roles:
  - geerlingguy.haproxy

  vars:
    haproxy_backend_servers:
    - name: docker_ansible_web_4
      address: docker_ansible_web_4:80
    - name: docker_ansible_web_5
      address: docker_ansible_web_5:80
  
  tasks:
  - name: retirer cookie
    lineinfile:
      path: /etc/haproxy/haproxy.cfg
      regexp: ".*cookie SERVERID.*"
      state: absent
