---
- hosts: dev_web
  tasks:
  - name: "installer apache2"
    apt: 
      name: apache2 
    notify: restart apache

  - name: "Demarer Apache"
    service: 
      name: apache2
      state: started
      enabled: yes

  - name: installer add-apt-repository
    apt:
      name: software-properties-common

  - name: add php repo
    shell: "add-apt-repository -y ppa:ondrej/php"
    environment: 
      LC_ALL: "C.UTF-8"
    args:
      creates: /etc/apt/sources.list.d/ondrej-ubuntu-php-xenial.list

  - name: installer php et modules
    apt:
      name: 
      - php7.3
      - php7.3-cli
      - php7.3-common
      - php7.3-curl
      - php7.3-gd
      - php7.3-json
      - php-apcu
      update_cache: yes
    notify: restart apache

  - name: cree le repertoire du site
    file: path=/var/www/html state=directory mode=0755

  - name: deployer index.php
    template:
      src: index.php
      dest: /var/www/html/index.php

  handlers:
  - name: restart apache
    service: name=apache2 state=restarted

  vars:
    template_var: coca